### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by kongdoo** [MrinalJain17/Human-Activity-Recognition#11]
Thank you so much!
I have this error.

ModuleNotFoundError: No module named 'utils'

Could you have an idea to solve it?

**Comment by MrinalJain17** [comment]
Looks like there is some issue with the imports. But I need more information.

(By any chance, did you place the notebook is some other directory, where there is no `utils.py` as in the repo?)
