### ISSUE TITLE
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

### ISSUE THREAD

**Issue by maghassiz** [MrinalJain17/Human-Activity-Recognition#13]
Hello, i will ask some question. when i trying to run your code i have error when try to reading training videos and one-hot encoding the training labels the error like this : 

"ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O."

what should i do? thanks

**Comment by 2151330** [comment]
Hi, @maghassiz 
Did you solve this problem？
Can you tell me the reason?
tks!
