### ISSUE TITLE
Cannot find installation of real FFmpeg (which comes with ffprobe)

### ISSUE THREAD

**Issue by bit-scientist** [MrinalJain17/Human-Activity-Recognition#5]
@MrinalJain17 I am following your  Jupyter Notebook and when I execute 

```
import numpy as np
import matplotlib.pyplot as plt
from utils import Videos


# The path of a sample video in the training data
sample_files = train_files[:1]

# An object of the class 'Videos'
reader = Videos(target_size=None, 
                to_gray=False)

# Loading the sample videos, in their original format
sample = reader.read_videos(sample_files)
print('\nShape of the sample data:', sample.shape)

# Displaying a frame from the sample video
plt.imshow(sample[0][300])
```
I get AssertionError that says 
```
 0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):

  File "<ipython-input-11-8fe6b4165331>", line 14, in <module>
    sample = reader.read_videos(sample_files)

  File "C:\Users\sohib\.spyder-py3\utils.py", line 70, in read_videos
    self._read_video(path) for path in tqdm(paths)

  File "C:\Users\sohib\.spyder-py3\utils.py", line 70, in <listcomp>
    self._read_video(path) for path in tqdm(paths)

  File "C:\Users\sohib\.spyder-py3\utils.py", line 126, in _read_video
    cap = FFmpegReader(filename=path)

  File "C:\Users\sohib\Anaconda3\envs\HAR\lib\site-packages\skvideo\io\ffmpeg.py", line 72, in __init__
    assert _HAS_FFMPEG, "Cannot find installation of real FFmpeg (which comes with ffprobe)."

AssertionError: Cannot find installation of real FFmpeg (which comes with ffprobe).
```
I created a new env in anaconda with python 3.5 and other required packages like sk-video, keras, tensorflow, tqdm, matplotlib, ffmpeg, ffprobe. But still error remains unfixed, what would you suggest doing?

**Comment by MrinalJain17** [comment]
Hi @git-sohib 

I believe that you are getting this error because either the `FFmpeg` codec is not installed on your system, or the location of the binaries has not been added to your `PATH`.

May I know:
- What OS are you using?
- How did you installed `FFmpeg`?

**Comment by bit-scientist** [comment]
@MrinalJain17  Thanks for your reply, I am on Win10.
I have an env in my Anaconda distribution, after activating an env, I just typed `conda install -c menpo ffmpeg` .

**Comment by MrinalJain17** [comment]
You need to install the `FFmpeg` binaries and the recommended way is explained here in the [README](https://github.com/MrinalJain17/Human-Activity-Recognition#requirements) - instructions for Windows users' is provided.

The rest of the packages can be installed using anaconda, but not FFmpeg (since it is not a *package*)

**Comment by bit-scientist** [comment]
@MrinalJain17 thanks. Is it enough to just add the location of binaries to the path in order to enable it in anaconda environment? There is no bin files inside the ffmpeg-4.0.2 folder, which location should be added to the path?

**Comment by MrinalJain17** [comment]
If you are using Windows, and assuming that you have downloaded `ffmpeg`, then on extracting the contents of the zip file, the binaries would be available inside a directory called `bin/`. You need to add the contents of that directory to your path.

**Comment by bit-scientist** [comment]
@MrinalJain17 I can assure that I downloaded ffmpeg from the link you provided, that's [here](https://www.ffmpeg.org/download.html) and it doesn't contain any bin folder. All it has after unzipping are
<img src="https://habrastorage.org/webt/p6/q6/du/p6q6duxotd44_q2j7hqocbpik6m.jpeg" />

**Comment by MrinalJain17** [comment]
You need to download the `Windows build`, not the compressed tar package. Use this [link](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.0.2-win64-static.zip) to download it, or configure it according to your needs from [here](https://ffmpeg.zeranoe.com/builds/).

**Comment by bit-scientist** [comment]
@MrinalJain17 Yeap I got it working, thank you for your appreciation

**Comment by MrinalJain17** [comment]
@git-sohib :+1:  Good to know that.

**Comment by tevinmoodley** [comment]
> You need to download the `Windows build`, not the compressed tar package. Use this [link](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.0.2-win64-static.zip) to download it, or configure it according to your needs from [here](https://ffmpeg.zeranoe.com/builds/).


Life saver, just to add, ensure you add the executables to ffmpeg folder that anaconda installs using pip, So the 3 executables in the bin folder must be added to this directory if you have the default anaconda env (\Anaconda3\Lib\site-packages\ffmpeg)

Additionally on your notebook, set the path environment skvideo.setFFmpegPath("/Users/#/Anaconda3/lib/site-packages/ffmpeg")

**Comment by MrinalJain17** [comment]
If you're using the conda package manager, just execute the following and it'll install `ffmpeg` as a Conda package.

    conda install ffmpeg -c mrinaljain17

More info [here](https://anaconda.org/mrinaljain17/ffmpeg) 😄

**Comment by bboylyg** [comment]
> > You need to download the `Windows build`, not the compressed tar package. Use this [link](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.0.2-win64-static.zip) to download it, or configure it according to your needs from [here](https://ffmpeg.zeranoe.com/builds/).
> 
> Life saver, just to add, ensure you add the executables to ffmpeg folder that anaconda installs using pip, So the 3 executables in the bin folder must be added to this directory if you have the default anaconda env (\Anaconda3\Lib\site-packages\ffmpeg)
> 
> Additionally on your notebook, set the path environment skvideo.setFFmpegPath("/Users/#/Anaconda3/lib/site-packages/ffmpeg")

thank you so much, i have solved the problems followed your instruction!

**Comment by MalathiKaliyappan** [comment]
@bboylyg   I'm also using anaconda env.  I don't know how to set path environment to notebook? can you help me

**Comment by MalathiKaliyappan** [comment]
@MrinalJain17  I'm following your notebook, when I run the code Mrinal Jain mention I got this error

```
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-16-a175c9b37020> in <module>()
     14 
     15 # Loading the sample videos, in their original format
---> 16 sample = reader.read_videos(sample_files)
     17 print('\nShape of the sample data:', sample.shape)
     18 

~\Desktop\intern\Human-Activity-Recognition\utils.py in read_videos(self, paths)
     68 
     69         list_of_videos = [
---> 70             self._read_video('C:\Users\malat\Desktop\intern\Human-Activity-Recognition\Data\boxing\video_file_01') for path in tqdm(paths)
     71         ]
     72 

~\Desktop\intern\Human-Activity-Recognition\utils.py in <listcomp>(.0)
     68 
     69         list_of_videos = [
---> 70             self._read_video('C:\Users\malat\Desktop\intern\Human-Activity-Recognition\Data\boxing\video_file_01') for path in tqdm(paths)
     71         ]
     72 

~\Desktop\intern\Human-Activity-Recognition\utils.py in _read_video(self, path)
    124         """
    125 
--> 126         cap = FFmpegReader(filename=path)
    127         list_of_frames = []
    128         self.fps = int(cap.inputfps)                  # Frame Rate

~\Anaconda3\lib\site-packages\skvideo\io\ffmpeg.py in __init__(self, filename, inputdict, outputdict, verbosity)
     70         """
     71         # check if FFMPEG exists in the path
---> 72         assert _HAS_FFMPEG, "Cannot find installation of real FFmpeg (which comes with ffprobe)."
     73 
     74         israw = 0

AssertionError: Cannot find installation of real FFmpeg (which comes with ffprobe).

``` 
can you give me suggestion to over come this..
